/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.openapi.model.AuditLogActor;
import com.openai.openapi.model.AuditLogApiKeyCreated;
import com.openai.openapi.model.AuditLogApiKeyDeleted;
import com.openai.openapi.model.AuditLogApiKeyUpdated;
import com.openai.openapi.model.AuditLogEventType;
import com.openai.openapi.model.AuditLogInviteAccepted;
import com.openai.openapi.model.AuditLogInviteSent;
import com.openai.openapi.model.AuditLogLoginFailed;
import com.openai.openapi.model.AuditLogOrganizationUpdated;
import com.openai.openapi.model.AuditLogProject;
import com.openai.openapi.model.AuditLogProjectArchived;
import com.openai.openapi.model.AuditLogProjectCreated;
import com.openai.openapi.model.AuditLogProjectUpdated;
import com.openai.openapi.model.AuditLogRateLimitDeleted;
import com.openai.openapi.model.AuditLogRateLimitUpdated;
import com.openai.openapi.model.AuditLogServiceAccountCreated;
import com.openai.openapi.model.AuditLogServiceAccountDeleted;
import com.openai.openapi.model.AuditLogServiceAccountUpdated;
import com.openai.openapi.model.AuditLogUserAdded;
import com.openai.openapi.model.AuditLogUserDeleted;
import com.openai.openapi.model.AuditLogUserUpdated;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * A log of a user action or configuration change within this organization.
 */
@JsonPropertyOrder({
  AuditLog.JSON_PROPERTY_ID,
  AuditLog.JSON_PROPERTY_TYPE,
  AuditLog.JSON_PROPERTY_EFFECTIVE_AT,
  AuditLog.JSON_PROPERTY_PROJECT,
  AuditLog.JSON_PROPERTY_ACTOR,
  AuditLog.JSON_PROPERTY_API_KEY_CREATED,
  AuditLog.JSON_PROPERTY_API_KEY_UPDATED,
  AuditLog.JSON_PROPERTY_API_KEY_DELETED,
  AuditLog.JSON_PROPERTY_INVITE_SENT,
  AuditLog.JSON_PROPERTY_INVITE_ACCEPTED,
  AuditLog.JSON_PROPERTY_INVITE_DELETED,
  AuditLog.JSON_PROPERTY_LOGIN_FAILED,
  AuditLog.JSON_PROPERTY_LOGOUT_FAILED,
  AuditLog.JSON_PROPERTY_ORGANIZATION_UPDATED,
  AuditLog.JSON_PROPERTY_PROJECT_CREATED,
  AuditLog.JSON_PROPERTY_PROJECT_UPDATED,
  AuditLog.JSON_PROPERTY_PROJECT_ARCHIVED,
  AuditLog.JSON_PROPERTY_RATE_LIMIT_UPDATED,
  AuditLog.JSON_PROPERTY_RATE_LIMIT_DELETED,
  AuditLog.JSON_PROPERTY_SERVICE_ACCOUNT_CREATED,
  AuditLog.JSON_PROPERTY_SERVICE_ACCOUNT_UPDATED,
  AuditLog.JSON_PROPERTY_SERVICE_ACCOUNT_DELETED,
  AuditLog.JSON_PROPERTY_USER_ADDED,
  AuditLog.JSON_PROPERTY_USER_UPDATED,
  AuditLog.JSON_PROPERTY_USER_DELETED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T10:23:25.420936454-05:00[US/Eastern]", comments = "Generator version: 7.11.0")
public class AuditLog {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private AuditLogEventType type;

  public static final String JSON_PROPERTY_EFFECTIVE_AT = "effective_at";
  @javax.annotation.Nonnull
  private Integer effectiveAt;

  public static final String JSON_PROPERTY_PROJECT = "project";
  @javax.annotation.Nullable
  private AuditLogProject project;

  public static final String JSON_PROPERTY_ACTOR = "actor";
  @javax.annotation.Nonnull
  private AuditLogActor actor;

  public static final String JSON_PROPERTY_API_KEY_CREATED = "api_key.created";
  @javax.annotation.Nullable
  private AuditLogApiKeyCreated apiKeyCreated;

  public static final String JSON_PROPERTY_API_KEY_UPDATED = "api_key.updated";
  @javax.annotation.Nullable
  private AuditLogApiKeyUpdated apiKeyUpdated;

  public static final String JSON_PROPERTY_API_KEY_DELETED = "api_key.deleted";
  @javax.annotation.Nullable
  private AuditLogApiKeyDeleted apiKeyDeleted;

  public static final String JSON_PROPERTY_INVITE_SENT = "invite.sent";
  @javax.annotation.Nullable
  private AuditLogInviteSent inviteSent;

  public static final String JSON_PROPERTY_INVITE_ACCEPTED = "invite.accepted";
  @javax.annotation.Nullable
  private AuditLogInviteAccepted inviteAccepted;

  public static final String JSON_PROPERTY_INVITE_DELETED = "invite.deleted";
  @javax.annotation.Nullable
  private AuditLogInviteAccepted inviteDeleted;

  public static final String JSON_PROPERTY_LOGIN_FAILED = "login.failed";
  @javax.annotation.Nullable
  private AuditLogLoginFailed loginFailed;

  public static final String JSON_PROPERTY_LOGOUT_FAILED = "logout.failed";
  @javax.annotation.Nullable
  private AuditLogLoginFailed logoutFailed;

  public static final String JSON_PROPERTY_ORGANIZATION_UPDATED = "organization.updated";
  @javax.annotation.Nullable
  private AuditLogOrganizationUpdated organizationUpdated;

  public static final String JSON_PROPERTY_PROJECT_CREATED = "project.created";
  @javax.annotation.Nullable
  private AuditLogProjectCreated projectCreated;

  public static final String JSON_PROPERTY_PROJECT_UPDATED = "project.updated";
  @javax.annotation.Nullable
  private AuditLogProjectUpdated projectUpdated;

  public static final String JSON_PROPERTY_PROJECT_ARCHIVED = "project.archived";
  @javax.annotation.Nullable
  private AuditLogProjectArchived projectArchived;

  public static final String JSON_PROPERTY_RATE_LIMIT_UPDATED = "rate_limit.updated";
  @javax.annotation.Nullable
  private AuditLogRateLimitUpdated rateLimitUpdated;

  public static final String JSON_PROPERTY_RATE_LIMIT_DELETED = "rate_limit.deleted";
  @javax.annotation.Nullable
  private AuditLogRateLimitDeleted rateLimitDeleted;

  public static final String JSON_PROPERTY_SERVICE_ACCOUNT_CREATED = "service_account.created";
  @javax.annotation.Nullable
  private AuditLogServiceAccountCreated serviceAccountCreated;

  public static final String JSON_PROPERTY_SERVICE_ACCOUNT_UPDATED = "service_account.updated";
  @javax.annotation.Nullable
  private AuditLogServiceAccountUpdated serviceAccountUpdated;

  public static final String JSON_PROPERTY_SERVICE_ACCOUNT_DELETED = "service_account.deleted";
  @javax.annotation.Nullable
  private AuditLogServiceAccountDeleted serviceAccountDeleted;

  public static final String JSON_PROPERTY_USER_ADDED = "user.added";
  @javax.annotation.Nullable
  private AuditLogUserAdded userAdded;

  public static final String JSON_PROPERTY_USER_UPDATED = "user.updated";
  @javax.annotation.Nullable
  private AuditLogUserUpdated userUpdated;

  public static final String JSON_PROPERTY_USER_DELETED = "user.deleted";
  @javax.annotation.Nullable
  private AuditLogUserDeleted userDeleted;

  public AuditLog() {
  }

  public AuditLog id(@javax.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The ID of this log.
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }

  public AuditLog type(@javax.annotation.Nonnull AuditLogEventType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AuditLogEventType getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull AuditLogEventType type) {
    this.type = type;
  }

  public AuditLog effectiveAt(@javax.annotation.Nonnull Integer effectiveAt) {
    
    this.effectiveAt = effectiveAt;
    return this;
  }

  /**
   * The Unix timestamp (in seconds) of the event.
   * @return effectiveAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EFFECTIVE_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEffectiveAt() {
    return effectiveAt;
  }


  @JsonProperty(JSON_PROPERTY_EFFECTIVE_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEffectiveAt(@javax.annotation.Nonnull Integer effectiveAt) {
    this.effectiveAt = effectiveAt;
  }

  public AuditLog project(@javax.annotation.Nullable AuditLogProject project) {
    
    this.project = project;
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogProject getProject() {
    return project;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProject(@javax.annotation.Nullable AuditLogProject project) {
    this.project = project;
  }

  public AuditLog actor(@javax.annotation.Nonnull AuditLogActor actor) {
    
    this.actor = actor;
    return this;
  }

  /**
   * Get actor
   * @return actor
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AuditLogActor getActor() {
    return actor;
  }


  @JsonProperty(JSON_PROPERTY_ACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActor(@javax.annotation.Nonnull AuditLogActor actor) {
    this.actor = actor;
  }

  public AuditLog apiKeyCreated(@javax.annotation.Nullable AuditLogApiKeyCreated apiKeyCreated) {
    
    this.apiKeyCreated = apiKeyCreated;
    return this;
  }

  /**
   * Get apiKeyCreated
   * @return apiKeyCreated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_KEY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogApiKeyCreated getApiKeyCreated() {
    return apiKeyCreated;
  }


  @JsonProperty(JSON_PROPERTY_API_KEY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiKeyCreated(@javax.annotation.Nullable AuditLogApiKeyCreated apiKeyCreated) {
    this.apiKeyCreated = apiKeyCreated;
  }

  public AuditLog apiKeyUpdated(@javax.annotation.Nullable AuditLogApiKeyUpdated apiKeyUpdated) {
    
    this.apiKeyUpdated = apiKeyUpdated;
    return this;
  }

  /**
   * Get apiKeyUpdated
   * @return apiKeyUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_KEY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogApiKeyUpdated getApiKeyUpdated() {
    return apiKeyUpdated;
  }


  @JsonProperty(JSON_PROPERTY_API_KEY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiKeyUpdated(@javax.annotation.Nullable AuditLogApiKeyUpdated apiKeyUpdated) {
    this.apiKeyUpdated = apiKeyUpdated;
  }

  public AuditLog apiKeyDeleted(@javax.annotation.Nullable AuditLogApiKeyDeleted apiKeyDeleted) {
    
    this.apiKeyDeleted = apiKeyDeleted;
    return this;
  }

  /**
   * Get apiKeyDeleted
   * @return apiKeyDeleted
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_KEY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogApiKeyDeleted getApiKeyDeleted() {
    return apiKeyDeleted;
  }


  @JsonProperty(JSON_PROPERTY_API_KEY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiKeyDeleted(@javax.annotation.Nullable AuditLogApiKeyDeleted apiKeyDeleted) {
    this.apiKeyDeleted = apiKeyDeleted;
  }

  public AuditLog inviteSent(@javax.annotation.Nullable AuditLogInviteSent inviteSent) {
    
    this.inviteSent = inviteSent;
    return this;
  }

  /**
   * Get inviteSent
   * @return inviteSent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVITE_SENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogInviteSent getInviteSent() {
    return inviteSent;
  }


  @JsonProperty(JSON_PROPERTY_INVITE_SENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInviteSent(@javax.annotation.Nullable AuditLogInviteSent inviteSent) {
    this.inviteSent = inviteSent;
  }

  public AuditLog inviteAccepted(@javax.annotation.Nullable AuditLogInviteAccepted inviteAccepted) {
    
    this.inviteAccepted = inviteAccepted;
    return this;
  }

  /**
   * Get inviteAccepted
   * @return inviteAccepted
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVITE_ACCEPTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogInviteAccepted getInviteAccepted() {
    return inviteAccepted;
  }


  @JsonProperty(JSON_PROPERTY_INVITE_ACCEPTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInviteAccepted(@javax.annotation.Nullable AuditLogInviteAccepted inviteAccepted) {
    this.inviteAccepted = inviteAccepted;
  }

  public AuditLog inviteDeleted(@javax.annotation.Nullable AuditLogInviteAccepted inviteDeleted) {
    
    this.inviteDeleted = inviteDeleted;
    return this;
  }

  /**
   * Get inviteDeleted
   * @return inviteDeleted
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVITE_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogInviteAccepted getInviteDeleted() {
    return inviteDeleted;
  }


  @JsonProperty(JSON_PROPERTY_INVITE_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInviteDeleted(@javax.annotation.Nullable AuditLogInviteAccepted inviteDeleted) {
    this.inviteDeleted = inviteDeleted;
  }

  public AuditLog loginFailed(@javax.annotation.Nullable AuditLogLoginFailed loginFailed) {
    
    this.loginFailed = loginFailed;
    return this;
  }

  /**
   * Get loginFailed
   * @return loginFailed
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGIN_FAILED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogLoginFailed getLoginFailed() {
    return loginFailed;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_FAILED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoginFailed(@javax.annotation.Nullable AuditLogLoginFailed loginFailed) {
    this.loginFailed = loginFailed;
  }

  public AuditLog logoutFailed(@javax.annotation.Nullable AuditLogLoginFailed logoutFailed) {
    
    this.logoutFailed = logoutFailed;
    return this;
  }

  /**
   * Get logoutFailed
   * @return logoutFailed
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGOUT_FAILED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogLoginFailed getLogoutFailed() {
    return logoutFailed;
  }


  @JsonProperty(JSON_PROPERTY_LOGOUT_FAILED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogoutFailed(@javax.annotation.Nullable AuditLogLoginFailed logoutFailed) {
    this.logoutFailed = logoutFailed;
  }

  public AuditLog organizationUpdated(@javax.annotation.Nullable AuditLogOrganizationUpdated organizationUpdated) {
    
    this.organizationUpdated = organizationUpdated;
    return this;
  }

  /**
   * Get organizationUpdated
   * @return organizationUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogOrganizationUpdated getOrganizationUpdated() {
    return organizationUpdated;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganizationUpdated(@javax.annotation.Nullable AuditLogOrganizationUpdated organizationUpdated) {
    this.organizationUpdated = organizationUpdated;
  }

  public AuditLog projectCreated(@javax.annotation.Nullable AuditLogProjectCreated projectCreated) {
    
    this.projectCreated = projectCreated;
    return this;
  }

  /**
   * Get projectCreated
   * @return projectCreated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECT_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogProjectCreated getProjectCreated() {
    return projectCreated;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectCreated(@javax.annotation.Nullable AuditLogProjectCreated projectCreated) {
    this.projectCreated = projectCreated;
  }

  public AuditLog projectUpdated(@javax.annotation.Nullable AuditLogProjectUpdated projectUpdated) {
    
    this.projectUpdated = projectUpdated;
    return this;
  }

  /**
   * Get projectUpdated
   * @return projectUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECT_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogProjectUpdated getProjectUpdated() {
    return projectUpdated;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectUpdated(@javax.annotation.Nullable AuditLogProjectUpdated projectUpdated) {
    this.projectUpdated = projectUpdated;
  }

  public AuditLog projectArchived(@javax.annotation.Nullable AuditLogProjectArchived projectArchived) {
    
    this.projectArchived = projectArchived;
    return this;
  }

  /**
   * Get projectArchived
   * @return projectArchived
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECT_ARCHIVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogProjectArchived getProjectArchived() {
    return projectArchived;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ARCHIVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectArchived(@javax.annotation.Nullable AuditLogProjectArchived projectArchived) {
    this.projectArchived = projectArchived;
  }

  public AuditLog rateLimitUpdated(@javax.annotation.Nullable AuditLogRateLimitUpdated rateLimitUpdated) {
    
    this.rateLimitUpdated = rateLimitUpdated;
    return this;
  }

  /**
   * Get rateLimitUpdated
   * @return rateLimitUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATE_LIMIT_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogRateLimitUpdated getRateLimitUpdated() {
    return rateLimitUpdated;
  }


  @JsonProperty(JSON_PROPERTY_RATE_LIMIT_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRateLimitUpdated(@javax.annotation.Nullable AuditLogRateLimitUpdated rateLimitUpdated) {
    this.rateLimitUpdated = rateLimitUpdated;
  }

  public AuditLog rateLimitDeleted(@javax.annotation.Nullable AuditLogRateLimitDeleted rateLimitDeleted) {
    
    this.rateLimitDeleted = rateLimitDeleted;
    return this;
  }

  /**
   * Get rateLimitDeleted
   * @return rateLimitDeleted
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATE_LIMIT_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogRateLimitDeleted getRateLimitDeleted() {
    return rateLimitDeleted;
  }


  @JsonProperty(JSON_PROPERTY_RATE_LIMIT_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRateLimitDeleted(@javax.annotation.Nullable AuditLogRateLimitDeleted rateLimitDeleted) {
    this.rateLimitDeleted = rateLimitDeleted;
  }

  public AuditLog serviceAccountCreated(@javax.annotation.Nullable AuditLogServiceAccountCreated serviceAccountCreated) {
    
    this.serviceAccountCreated = serviceAccountCreated;
    return this;
  }

  /**
   * Get serviceAccountCreated
   * @return serviceAccountCreated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_ACCOUNT_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogServiceAccountCreated getServiceAccountCreated() {
    return serviceAccountCreated;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_ACCOUNT_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceAccountCreated(@javax.annotation.Nullable AuditLogServiceAccountCreated serviceAccountCreated) {
    this.serviceAccountCreated = serviceAccountCreated;
  }

  public AuditLog serviceAccountUpdated(@javax.annotation.Nullable AuditLogServiceAccountUpdated serviceAccountUpdated) {
    
    this.serviceAccountUpdated = serviceAccountUpdated;
    return this;
  }

  /**
   * Get serviceAccountUpdated
   * @return serviceAccountUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_ACCOUNT_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogServiceAccountUpdated getServiceAccountUpdated() {
    return serviceAccountUpdated;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_ACCOUNT_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceAccountUpdated(@javax.annotation.Nullable AuditLogServiceAccountUpdated serviceAccountUpdated) {
    this.serviceAccountUpdated = serviceAccountUpdated;
  }

  public AuditLog serviceAccountDeleted(@javax.annotation.Nullable AuditLogServiceAccountDeleted serviceAccountDeleted) {
    
    this.serviceAccountDeleted = serviceAccountDeleted;
    return this;
  }

  /**
   * Get serviceAccountDeleted
   * @return serviceAccountDeleted
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_ACCOUNT_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogServiceAccountDeleted getServiceAccountDeleted() {
    return serviceAccountDeleted;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_ACCOUNT_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceAccountDeleted(@javax.annotation.Nullable AuditLogServiceAccountDeleted serviceAccountDeleted) {
    this.serviceAccountDeleted = serviceAccountDeleted;
  }

  public AuditLog userAdded(@javax.annotation.Nullable AuditLogUserAdded userAdded) {
    
    this.userAdded = userAdded;
    return this;
  }

  /**
   * Get userAdded
   * @return userAdded
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ADDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogUserAdded getUserAdded() {
    return userAdded;
  }


  @JsonProperty(JSON_PROPERTY_USER_ADDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserAdded(@javax.annotation.Nullable AuditLogUserAdded userAdded) {
    this.userAdded = userAdded;
  }

  public AuditLog userUpdated(@javax.annotation.Nullable AuditLogUserUpdated userUpdated) {
    
    this.userUpdated = userUpdated;
    return this;
  }

  /**
   * Get userUpdated
   * @return userUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogUserUpdated getUserUpdated() {
    return userUpdated;
  }


  @JsonProperty(JSON_PROPERTY_USER_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserUpdated(@javax.annotation.Nullable AuditLogUserUpdated userUpdated) {
    this.userUpdated = userUpdated;
  }

  public AuditLog userDeleted(@javax.annotation.Nullable AuditLogUserDeleted userDeleted) {
    
    this.userDeleted = userDeleted;
    return this;
  }

  /**
   * Get userDeleted
   * @return userDeleted
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLogUserDeleted getUserDeleted() {
    return userDeleted;
  }


  @JsonProperty(JSON_PROPERTY_USER_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserDeleted(@javax.annotation.Nullable AuditLogUserDeleted userDeleted) {
    this.userDeleted = userDeleted;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditLog auditLog = (AuditLog) o;
    return Objects.equals(this.id, auditLog.id) &&
        Objects.equals(this.type, auditLog.type) &&
        Objects.equals(this.effectiveAt, auditLog.effectiveAt) &&
        Objects.equals(this.project, auditLog.project) &&
        Objects.equals(this.actor, auditLog.actor) &&
        Objects.equals(this.apiKeyCreated, auditLog.apiKeyCreated) &&
        Objects.equals(this.apiKeyUpdated, auditLog.apiKeyUpdated) &&
        Objects.equals(this.apiKeyDeleted, auditLog.apiKeyDeleted) &&
        Objects.equals(this.inviteSent, auditLog.inviteSent) &&
        Objects.equals(this.inviteAccepted, auditLog.inviteAccepted) &&
        Objects.equals(this.inviteDeleted, auditLog.inviteDeleted) &&
        Objects.equals(this.loginFailed, auditLog.loginFailed) &&
        Objects.equals(this.logoutFailed, auditLog.logoutFailed) &&
        Objects.equals(this.organizationUpdated, auditLog.organizationUpdated) &&
        Objects.equals(this.projectCreated, auditLog.projectCreated) &&
        Objects.equals(this.projectUpdated, auditLog.projectUpdated) &&
        Objects.equals(this.projectArchived, auditLog.projectArchived) &&
        Objects.equals(this.rateLimitUpdated, auditLog.rateLimitUpdated) &&
        Objects.equals(this.rateLimitDeleted, auditLog.rateLimitDeleted) &&
        Objects.equals(this.serviceAccountCreated, auditLog.serviceAccountCreated) &&
        Objects.equals(this.serviceAccountUpdated, auditLog.serviceAccountUpdated) &&
        Objects.equals(this.serviceAccountDeleted, auditLog.serviceAccountDeleted) &&
        Objects.equals(this.userAdded, auditLog.userAdded) &&
        Objects.equals(this.userUpdated, auditLog.userUpdated) &&
        Objects.equals(this.userDeleted, auditLog.userDeleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, effectiveAt, project, actor, apiKeyCreated, apiKeyUpdated, apiKeyDeleted, inviteSent, inviteAccepted, inviteDeleted, loginFailed, logoutFailed, organizationUpdated, projectCreated, projectUpdated, projectArchived, rateLimitUpdated, rateLimitDeleted, serviceAccountCreated, serviceAccountUpdated, serviceAccountDeleted, userAdded, userUpdated, userDeleted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditLog {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    effectiveAt: ").append(toIndentedString(effectiveAt)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
    sb.append("    apiKeyCreated: ").append(toIndentedString(apiKeyCreated)).append("\n");
    sb.append("    apiKeyUpdated: ").append(toIndentedString(apiKeyUpdated)).append("\n");
    sb.append("    apiKeyDeleted: ").append(toIndentedString(apiKeyDeleted)).append("\n");
    sb.append("    inviteSent: ").append(toIndentedString(inviteSent)).append("\n");
    sb.append("    inviteAccepted: ").append(toIndentedString(inviteAccepted)).append("\n");
    sb.append("    inviteDeleted: ").append(toIndentedString(inviteDeleted)).append("\n");
    sb.append("    loginFailed: ").append(toIndentedString(loginFailed)).append("\n");
    sb.append("    logoutFailed: ").append(toIndentedString(logoutFailed)).append("\n");
    sb.append("    organizationUpdated: ").append(toIndentedString(organizationUpdated)).append("\n");
    sb.append("    projectCreated: ").append(toIndentedString(projectCreated)).append("\n");
    sb.append("    projectUpdated: ").append(toIndentedString(projectUpdated)).append("\n");
    sb.append("    projectArchived: ").append(toIndentedString(projectArchived)).append("\n");
    sb.append("    rateLimitUpdated: ").append(toIndentedString(rateLimitUpdated)).append("\n");
    sb.append("    rateLimitDeleted: ").append(toIndentedString(rateLimitDeleted)).append("\n");
    sb.append("    serviceAccountCreated: ").append(toIndentedString(serviceAccountCreated)).append("\n");
    sb.append("    serviceAccountUpdated: ").append(toIndentedString(serviceAccountUpdated)).append("\n");
    sb.append("    serviceAccountDeleted: ").append(toIndentedString(serviceAccountDeleted)).append("\n");
    sb.append("    userAdded: ").append(toIndentedString(userAdded)).append("\n");
    sb.append("    userUpdated: ").append(toIndentedString(userUpdated)).append("\n");
    sb.append("    userDeleted: ").append(toIndentedString(userDeleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      try {
        joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `effective_at` to the URL query string
    if (getEffectiveAt() != null) {
      try {
        joiner.add(String.format("%seffective_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEffectiveAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `project` to the URL query string
    if (getProject() != null) {
      joiner.add(getProject().toUrlQueryString(prefix + "project" + suffix));
    }

    // add `actor` to the URL query string
    if (getActor() != null) {
      joiner.add(getActor().toUrlQueryString(prefix + "actor" + suffix));
    }

    // add `api_key.created` to the URL query string
    if (getApiKeyCreated() != null) {
      joiner.add(getApiKeyCreated().toUrlQueryString(prefix + "api_key.created" + suffix));
    }

    // add `api_key.updated` to the URL query string
    if (getApiKeyUpdated() != null) {
      joiner.add(getApiKeyUpdated().toUrlQueryString(prefix + "api_key.updated" + suffix));
    }

    // add `api_key.deleted` to the URL query string
    if (getApiKeyDeleted() != null) {
      joiner.add(getApiKeyDeleted().toUrlQueryString(prefix + "api_key.deleted" + suffix));
    }

    // add `invite.sent` to the URL query string
    if (getInviteSent() != null) {
      joiner.add(getInviteSent().toUrlQueryString(prefix + "invite.sent" + suffix));
    }

    // add `invite.accepted` to the URL query string
    if (getInviteAccepted() != null) {
      joiner.add(getInviteAccepted().toUrlQueryString(prefix + "invite.accepted" + suffix));
    }

    // add `invite.deleted` to the URL query string
    if (getInviteDeleted() != null) {
      joiner.add(getInviteDeleted().toUrlQueryString(prefix + "invite.deleted" + suffix));
    }

    // add `login.failed` to the URL query string
    if (getLoginFailed() != null) {
      joiner.add(getLoginFailed().toUrlQueryString(prefix + "login.failed" + suffix));
    }

    // add `logout.failed` to the URL query string
    if (getLogoutFailed() != null) {
      joiner.add(getLogoutFailed().toUrlQueryString(prefix + "logout.failed" + suffix));
    }

    // add `organization.updated` to the URL query string
    if (getOrganizationUpdated() != null) {
      joiner.add(getOrganizationUpdated().toUrlQueryString(prefix + "organization.updated" + suffix));
    }

    // add `project.created` to the URL query string
    if (getProjectCreated() != null) {
      joiner.add(getProjectCreated().toUrlQueryString(prefix + "project.created" + suffix));
    }

    // add `project.updated` to the URL query string
    if (getProjectUpdated() != null) {
      joiner.add(getProjectUpdated().toUrlQueryString(prefix + "project.updated" + suffix));
    }

    // add `project.archived` to the URL query string
    if (getProjectArchived() != null) {
      joiner.add(getProjectArchived().toUrlQueryString(prefix + "project.archived" + suffix));
    }

    // add `rate_limit.updated` to the URL query string
    if (getRateLimitUpdated() != null) {
      joiner.add(getRateLimitUpdated().toUrlQueryString(prefix + "rate_limit.updated" + suffix));
    }

    // add `rate_limit.deleted` to the URL query string
    if (getRateLimitDeleted() != null) {
      joiner.add(getRateLimitDeleted().toUrlQueryString(prefix + "rate_limit.deleted" + suffix));
    }

    // add `service_account.created` to the URL query string
    if (getServiceAccountCreated() != null) {
      joiner.add(getServiceAccountCreated().toUrlQueryString(prefix + "service_account.created" + suffix));
    }

    // add `service_account.updated` to the URL query string
    if (getServiceAccountUpdated() != null) {
      joiner.add(getServiceAccountUpdated().toUrlQueryString(prefix + "service_account.updated" + suffix));
    }

    // add `service_account.deleted` to the URL query string
    if (getServiceAccountDeleted() != null) {
      joiner.add(getServiceAccountDeleted().toUrlQueryString(prefix + "service_account.deleted" + suffix));
    }

    // add `user.added` to the URL query string
    if (getUserAdded() != null) {
      joiner.add(getUserAdded().toUrlQueryString(prefix + "user.added" + suffix));
    }

    // add `user.updated` to the URL query string
    if (getUserUpdated() != null) {
      joiner.add(getUserUpdated().toUrlQueryString(prefix + "user.updated" + suffix));
    }

    // add `user.deleted` to the URL query string
    if (getUserDeleted() != null) {
      joiner.add(getUserDeleted().toUrlQueryString(prefix + "user.deleted" + suffix));
    }

    return joiner.toString();
  }

}

