/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.openapi.model.FineTuneMethod;
import com.openai.openapi.model.FineTuningJobError;
import com.openai.openapi.model.FineTuningJobHyperparameters;
import com.openai.openapi.model.FineTuningJobIntegrationsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * The &#x60;fine_tuning.job&#x60; object represents a fine-tuning job that has been created through the API. 
 */
@JsonPropertyOrder({
  FineTuningJob.JSON_PROPERTY_ID,
  FineTuningJob.JSON_PROPERTY_CREATED_AT,
  FineTuningJob.JSON_PROPERTY_ERROR,
  FineTuningJob.JSON_PROPERTY_FINE_TUNED_MODEL,
  FineTuningJob.JSON_PROPERTY_FINISHED_AT,
  FineTuningJob.JSON_PROPERTY_HYPERPARAMETERS,
  FineTuningJob.JSON_PROPERTY_MODEL,
  FineTuningJob.JSON_PROPERTY_OBJECT,
  FineTuningJob.JSON_PROPERTY_ORGANIZATION_ID,
  FineTuningJob.JSON_PROPERTY_RESULT_FILES,
  FineTuningJob.JSON_PROPERTY_STATUS,
  FineTuningJob.JSON_PROPERTY_TRAINED_TOKENS,
  FineTuningJob.JSON_PROPERTY_TRAINING_FILE,
  FineTuningJob.JSON_PROPERTY_VALIDATION_FILE,
  FineTuningJob.JSON_PROPERTY_INTEGRATIONS,
  FineTuningJob.JSON_PROPERTY_SEED,
  FineTuningJob.JSON_PROPERTY_ESTIMATED_FINISH,
  FineTuningJob.JSON_PROPERTY_METHOD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T10:23:25.420936454-05:00[US/Eastern]", comments = "Generator version: 7.11.0")
public class FineTuningJob {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nonnull
  private Integer createdAt;

  public static final String JSON_PROPERTY_ERROR = "error";
  @javax.annotation.Nullable
  private FineTuningJobError error;

  public static final String JSON_PROPERTY_FINE_TUNED_MODEL = "fine_tuned_model";
  @javax.annotation.Nullable
  private String fineTunedModel;

  public static final String JSON_PROPERTY_FINISHED_AT = "finished_at";
  @javax.annotation.Nullable
  private Integer finishedAt;

  public static final String JSON_PROPERTY_HYPERPARAMETERS = "hyperparameters";
  @javax.annotation.Nonnull
  private FineTuningJobHyperparameters hyperparameters;

  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nonnull
  private String model;

  /**
   * The object type, which is always \&quot;fine_tuning.job\&quot;.
   */
  public enum ObjectEnum {
    FINE_TUNING_JOB(String.valueOf("fine_tuning.job"));

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectEnum fromValue(String value) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nonnull
  private ObjectEnum _object;

  public static final String JSON_PROPERTY_ORGANIZATION_ID = "organization_id";
  @javax.annotation.Nonnull
  private String organizationId;

  public static final String JSON_PROPERTY_RESULT_FILES = "result_files";
  @javax.annotation.Nonnull
  private List<String> resultFiles = new ArrayList<>();

  /**
   * The current status of the fine-tuning job, which can be either &#x60;validating_files&#x60;, &#x60;queued&#x60;, &#x60;running&#x60;, &#x60;succeeded&#x60;, &#x60;failed&#x60;, or &#x60;cancelled&#x60;.
   */
  public enum StatusEnum {
    VALIDATING_FILES(String.valueOf("validating_files")),
    
    QUEUED(String.valueOf("queued")),
    
    RUNNING(String.valueOf("running")),
    
    SUCCEEDED(String.valueOf("succeeded")),
    
    FAILED(String.valueOf("failed")),
    
    CANCELLED(String.valueOf("cancelled"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_TRAINED_TOKENS = "trained_tokens";
  @javax.annotation.Nullable
  private Integer trainedTokens;

  public static final String JSON_PROPERTY_TRAINING_FILE = "training_file";
  @javax.annotation.Nonnull
  private String trainingFile;

  public static final String JSON_PROPERTY_VALIDATION_FILE = "validation_file";
  @javax.annotation.Nullable
  private String validationFile;

  public static final String JSON_PROPERTY_INTEGRATIONS = "integrations";
  @javax.annotation.Nullable
  private JsonNullable<List<FineTuningJobIntegrationsInner>> integrations = JsonNullable.<List<FineTuningJobIntegrationsInner>>undefined();

  public static final String JSON_PROPERTY_SEED = "seed";
  @javax.annotation.Nonnull
  private Integer seed;

  public static final String JSON_PROPERTY_ESTIMATED_FINISH = "estimated_finish";
  @javax.annotation.Nullable
  private JsonNullable<Integer> estimatedFinish = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_METHOD = "method";
  @javax.annotation.Nullable
  private FineTuneMethod method;

  public FineTuningJob() {
  }

  public FineTuningJob id(@javax.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The object identifier, which can be referenced in the API endpoints.
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }

  public FineTuningJob createdAt(@javax.annotation.Nonnull Integer createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The Unix timestamp (in seconds) for when the fine-tuning job was created.
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull Integer createdAt) {
    this.createdAt = createdAt;
  }

  public FineTuningJob error(@javax.annotation.Nullable FineTuningJobError error) {
    
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FineTuningJobError getError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setError(@javax.annotation.Nullable FineTuningJobError error) {
    this.error = error;
  }

  public FineTuningJob fineTunedModel(@javax.annotation.Nullable String fineTunedModel) {
    
    this.fineTunedModel = fineTunedModel;
    return this;
  }

  /**
   * The name of the fine-tuned model that is being created. The value will be null if the fine-tuning job is still running.
   * @return fineTunedModel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINE_TUNED_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFineTunedModel() {
    return fineTunedModel;
  }


  @JsonProperty(JSON_PROPERTY_FINE_TUNED_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFineTunedModel(@javax.annotation.Nullable String fineTunedModel) {
    this.fineTunedModel = fineTunedModel;
  }

  public FineTuningJob finishedAt(@javax.annotation.Nullable Integer finishedAt) {
    
    this.finishedAt = finishedAt;
    return this;
  }

  /**
   * The Unix timestamp (in seconds) for when the fine-tuning job was finished. The value will be null if the fine-tuning job is still running.
   * @return finishedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINISHED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFinishedAt() {
    return finishedAt;
  }


  @JsonProperty(JSON_PROPERTY_FINISHED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFinishedAt(@javax.annotation.Nullable Integer finishedAt) {
    this.finishedAt = finishedAt;
  }

  public FineTuningJob hyperparameters(@javax.annotation.Nonnull FineTuningJobHyperparameters hyperparameters) {
    
    this.hyperparameters = hyperparameters;
    return this;
  }

  /**
   * Get hyperparameters
   * @return hyperparameters
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HYPERPARAMETERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FineTuningJobHyperparameters getHyperparameters() {
    return hyperparameters;
  }


  @JsonProperty(JSON_PROPERTY_HYPERPARAMETERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHyperparameters(@javax.annotation.Nonnull FineTuningJobHyperparameters hyperparameters) {
    this.hyperparameters = hyperparameters;
  }

  public FineTuningJob model(@javax.annotation.Nonnull String model) {
    
    this.model = model;
    return this;
  }

  /**
   * The base model that is being fine-tuned.
   * @return model
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModel() {
    return model;
  }


  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@javax.annotation.Nonnull String model) {
    this.model = model;
  }

  public FineTuningJob _object(@javax.annotation.Nonnull ObjectEnum _object) {
    
    this._object = _object;
    return this;
  }

  /**
   * The object type, which is always \&quot;fine_tuning.job\&quot;.
   * @return _object
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ObjectEnum getObject() {
    return _object;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObject(@javax.annotation.Nonnull ObjectEnum _object) {
    this._object = _object;
  }

  public FineTuningJob organizationId(@javax.annotation.Nonnull String organizationId) {
    
    this.organizationId = organizationId;
    return this;
  }

  /**
   * The organization that owns the fine-tuning job.
   * @return organizationId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrganizationId() {
    return organizationId;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganizationId(@javax.annotation.Nonnull String organizationId) {
    this.organizationId = organizationId;
  }

  public FineTuningJob resultFiles(@javax.annotation.Nonnull List<String> resultFiles) {
    
    this.resultFiles = resultFiles;
    return this;
  }

  public FineTuningJob addResultFilesItem(String resultFilesItem) {
    if (this.resultFiles == null) {
      this.resultFiles = new ArrayList<>();
    }
    this.resultFiles.add(resultFilesItem);
    return this;
  }

  /**
   * The compiled results file ID(s) for the fine-tuning job. You can retrieve the results with the [Files API](/docs/api-reference/files/retrieve-contents).
   * @return resultFiles
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESULT_FILES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getResultFiles() {
    return resultFiles;
  }


  @JsonProperty(JSON_PROPERTY_RESULT_FILES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResultFiles(@javax.annotation.Nonnull List<String> resultFiles) {
    this.resultFiles = resultFiles;
  }

  public FineTuningJob status(@javax.annotation.Nonnull StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * The current status of the fine-tuning job, which can be either &#x60;validating_files&#x60;, &#x60;queued&#x60;, &#x60;running&#x60;, &#x60;succeeded&#x60;, &#x60;failed&#x60;, or &#x60;cancelled&#x60;.
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }

  public FineTuningJob trainedTokens(@javax.annotation.Nullable Integer trainedTokens) {
    
    this.trainedTokens = trainedTokens;
    return this;
  }

  /**
   * The total number of billable tokens processed by this fine-tuning job. The value will be null if the fine-tuning job is still running.
   * @return trainedTokens
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAINED_TOKENS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTrainedTokens() {
    return trainedTokens;
  }


  @JsonProperty(JSON_PROPERTY_TRAINED_TOKENS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrainedTokens(@javax.annotation.Nullable Integer trainedTokens) {
    this.trainedTokens = trainedTokens;
  }

  public FineTuningJob trainingFile(@javax.annotation.Nonnull String trainingFile) {
    
    this.trainingFile = trainingFile;
    return this;
  }

  /**
   * The file ID used for training. You can retrieve the training data with the [Files API](/docs/api-reference/files/retrieve-contents).
   * @return trainingFile
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRAINING_FILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTrainingFile() {
    return trainingFile;
  }


  @JsonProperty(JSON_PROPERTY_TRAINING_FILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrainingFile(@javax.annotation.Nonnull String trainingFile) {
    this.trainingFile = trainingFile;
  }

  public FineTuningJob validationFile(@javax.annotation.Nullable String validationFile) {
    
    this.validationFile = validationFile;
    return this;
  }

  /**
   * The file ID used for validation. You can retrieve the validation results with the [Files API](/docs/api-reference/files/retrieve-contents).
   * @return validationFile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALIDATION_FILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValidationFile() {
    return validationFile;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATION_FILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidationFile(@javax.annotation.Nullable String validationFile) {
    this.validationFile = validationFile;
  }

  public FineTuningJob integrations(@javax.annotation.Nullable List<FineTuningJobIntegrationsInner> integrations) {
    this.integrations = JsonNullable.<List<FineTuningJobIntegrationsInner>>of(integrations);
    
    return this;
  }

  public FineTuningJob addIntegrationsItem(FineTuningJobIntegrationsInner integrationsItem) {
    if (this.integrations == null || !this.integrations.isPresent()) {
      this.integrations = JsonNullable.<List<FineTuningJobIntegrationsInner>>of(new ArrayList<>());
    }
    try {
      this.integrations.get().add(integrationsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * A list of integrations to enable for this fine-tuning job.
   * @return integrations
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<FineTuningJobIntegrationsInner> getIntegrations() {
        return integrations.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INTEGRATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<FineTuningJobIntegrationsInner>> getIntegrations_JsonNullable() {
    return integrations;
  }
  
  @JsonProperty(JSON_PROPERTY_INTEGRATIONS)
  public void setIntegrations_JsonNullable(JsonNullable<List<FineTuningJobIntegrationsInner>> integrations) {
    this.integrations = integrations;
  }

  public void setIntegrations(@javax.annotation.Nullable List<FineTuningJobIntegrationsInner> integrations) {
    this.integrations = JsonNullable.<List<FineTuningJobIntegrationsInner>>of(integrations);
  }

  public FineTuningJob seed(@javax.annotation.Nonnull Integer seed) {
    
    this.seed = seed;
    return this;
  }

  /**
   * The seed used for the fine-tuning job.
   * @return seed
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSeed() {
    return seed;
  }


  @JsonProperty(JSON_PROPERTY_SEED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeed(@javax.annotation.Nonnull Integer seed) {
    this.seed = seed;
  }

  public FineTuningJob estimatedFinish(@javax.annotation.Nullable Integer estimatedFinish) {
    this.estimatedFinish = JsonNullable.<Integer>of(estimatedFinish);
    
    return this;
  }

  /**
   * The Unix timestamp (in seconds) for when the fine-tuning job is estimated to finish. The value will be null if the fine-tuning job is not running.
   * @return estimatedFinish
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Integer getEstimatedFinish() {
        return estimatedFinish.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ESTIMATED_FINISH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getEstimatedFinish_JsonNullable() {
    return estimatedFinish;
  }
  
  @JsonProperty(JSON_PROPERTY_ESTIMATED_FINISH)
  public void setEstimatedFinish_JsonNullable(JsonNullable<Integer> estimatedFinish) {
    this.estimatedFinish = estimatedFinish;
  }

  public void setEstimatedFinish(@javax.annotation.Nullable Integer estimatedFinish) {
    this.estimatedFinish = JsonNullable.<Integer>of(estimatedFinish);
  }

  public FineTuningJob method(@javax.annotation.Nullable FineTuneMethod method) {
    
    this.method = method;
    return this;
  }

  /**
   * Get method
   * @return method
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FineTuneMethod getMethod() {
    return method;
  }


  @JsonProperty(JSON_PROPERTY_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethod(@javax.annotation.Nullable FineTuneMethod method) {
    this.method = method;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FineTuningJob fineTuningJob = (FineTuningJob) o;
    return Objects.equals(this.id, fineTuningJob.id) &&
        Objects.equals(this.createdAt, fineTuningJob.createdAt) &&
        Objects.equals(this.error, fineTuningJob.error) &&
        Objects.equals(this.fineTunedModel, fineTuningJob.fineTunedModel) &&
        Objects.equals(this.finishedAt, fineTuningJob.finishedAt) &&
        Objects.equals(this.hyperparameters, fineTuningJob.hyperparameters) &&
        Objects.equals(this.model, fineTuningJob.model) &&
        Objects.equals(this._object, fineTuningJob._object) &&
        Objects.equals(this.organizationId, fineTuningJob.organizationId) &&
        Objects.equals(this.resultFiles, fineTuningJob.resultFiles) &&
        Objects.equals(this.status, fineTuningJob.status) &&
        Objects.equals(this.trainedTokens, fineTuningJob.trainedTokens) &&
        Objects.equals(this.trainingFile, fineTuningJob.trainingFile) &&
        Objects.equals(this.validationFile, fineTuningJob.validationFile) &&
        equalsNullable(this.integrations, fineTuningJob.integrations) &&
        Objects.equals(this.seed, fineTuningJob.seed) &&
        equalsNullable(this.estimatedFinish, fineTuningJob.estimatedFinish) &&
        Objects.equals(this.method, fineTuningJob.method);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, error, fineTunedModel, finishedAt, hyperparameters, model, _object, organizationId, resultFiles, status, trainedTokens, trainingFile, validationFile, hashCodeNullable(integrations), seed, hashCodeNullable(estimatedFinish), method);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FineTuningJob {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    fineTunedModel: ").append(toIndentedString(fineTunedModel)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    hyperparameters: ").append(toIndentedString(hyperparameters)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    resultFiles: ").append(toIndentedString(resultFiles)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    trainedTokens: ").append(toIndentedString(trainedTokens)).append("\n");
    sb.append("    trainingFile: ").append(toIndentedString(trainingFile)).append("\n");
    sb.append("    validationFile: ").append(toIndentedString(validationFile)).append("\n");
    sb.append("    integrations: ").append(toIndentedString(integrations)).append("\n");
    sb.append("    seed: ").append(toIndentedString(seed)).append("\n");
    sb.append("    estimatedFinish: ").append(toIndentedString(estimatedFinish)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      try {
        joiner.add(String.format("%screated_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreatedAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(getError().toUrlQueryString(prefix + "error" + suffix));
    }

    // add `fine_tuned_model` to the URL query string
    if (getFineTunedModel() != null) {
      try {
        joiner.add(String.format("%sfine_tuned_model%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFineTunedModel()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `finished_at` to the URL query string
    if (getFinishedAt() != null) {
      try {
        joiner.add(String.format("%sfinished_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFinishedAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `hyperparameters` to the URL query string
    if (getHyperparameters() != null) {
      joiner.add(getHyperparameters().toUrlQueryString(prefix + "hyperparameters" + suffix));
    }

    // add `model` to the URL query string
    if (getModel() != null) {
      try {
        joiner.add(String.format("%smodel%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getModel()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `object` to the URL query string
    if (getObject() != null) {
      try {
        joiner.add(String.format("%sobject%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getObject()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `organization_id` to the URL query string
    if (getOrganizationId() != null) {
      try {
        joiner.add(String.format("%sorganization_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getOrganizationId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `result_files` to the URL query string
    if (getResultFiles() != null) {
      for (int i = 0; i < getResultFiles().size(); i++) {
        try {
          joiner.add(String.format("%sresult_files%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getResultFiles().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      try {
        joiner.add(String.format("%sstatus%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStatus()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `trained_tokens` to the URL query string
    if (getTrainedTokens() != null) {
      try {
        joiner.add(String.format("%strained_tokens%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTrainedTokens()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `training_file` to the URL query string
    if (getTrainingFile() != null) {
      try {
        joiner.add(String.format("%straining_file%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTrainingFile()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `validation_file` to the URL query string
    if (getValidationFile() != null) {
      try {
        joiner.add(String.format("%svalidation_file%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getValidationFile()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `integrations` to the URL query string
    if (getIntegrations() != null) {
      for (int i = 0; i < getIntegrations().size(); i++) {
        if (getIntegrations().get(i) != null) {
          joiner.add(getIntegrations().get(i).toUrlQueryString(String.format("%sintegrations%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `seed` to the URL query string
    if (getSeed() != null) {
      try {
        joiner.add(String.format("%sseed%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSeed()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `estimated_finish` to the URL query string
    if (getEstimatedFinish() != null) {
      try {
        joiner.add(String.format("%sestimated_finish%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEstimatedFinish()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `method` to the URL query string
    if (getMethod() != null) {
      joiner.add(getMethod().toUrlQueryString(prefix + "method" + suffix));
    }

    return joiner.toString();
  }

}

