/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChatCompletionResponseMessageFunctionCall
 */
class ChatCompletionResponseMessageFunctionCallTest {
    private final ChatCompletionResponseMessageFunctionCall model = new ChatCompletionResponseMessageFunctionCall();

    /**
     * Model tests for ChatCompletionResponseMessageFunctionCall
     */
    @Test
    void testChatCompletionResponseMessageFunctionCall() {
        // TODO: test ChatCompletionResponseMessageFunctionCall
    }

    /**
     * Test the property 'arguments'
     */
    @Test
    void argumentsTest() {
        // TODO: test arguments
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

}
