/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import com.fasterxml.jackson.annotation.JsonTypeName;
import com.openai.openapi.model.ChatCompletionRequestToolMessageContentPart;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChatCompletionRequestToolMessageContent
 */
class ChatCompletionRequestToolMessageContentTest {
    private final ChatCompletionRequestToolMessageContent model = new ChatCompletionRequestToolMessageContent();

    /**
     * Model tests for ChatCompletionRequestToolMessageContent
     */
    @Test
    void testChatCompletionRequestToolMessageContent() {
        // TODO: test ChatCompletionRequestToolMessageContent
    }

}
