/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateFineTuningJobRequestIntegrationsInnerWandb
 */
class CreateFineTuningJobRequestIntegrationsInnerWandbTest {
    private final CreateFineTuningJobRequestIntegrationsInnerWandb model = new CreateFineTuningJobRequestIntegrationsInnerWandb();

    /**
     * Model tests for CreateFineTuningJobRequestIntegrationsInnerWandb
     */
    @Test
    void testCreateFineTuningJobRequestIntegrationsInnerWandb() {
        // TODO: test CreateFineTuningJobRequestIntegrationsInnerWandb
    }

    /**
     * Test the property 'project'
     */
    @Test
    void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'entity'
     */
    @Test
    void entityTest() {
        // TODO: test entity
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

}
