/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.openapi.model.CompletionUsage;
import com.openai.openapi.model.CreateCompletionResponseChoicesInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateCompletionResponse
 */
class CreateCompletionResponseTest {
    private final CreateCompletionResponse model = new CreateCompletionResponse();

    /**
     * Model tests for CreateCompletionResponse
     */
    @Test
    void testCreateCompletionResponse() {
        // TODO: test CreateCompletionResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'choices'
     */
    @Test
    void choicesTest() {
        // TODO: test choices
    }

    /**
     * Test the property 'created'
     */
    @Test
    void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'model'
     */
    @Test
    void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'systemFingerprint'
     */
    @Test
    void systemFingerprintTest() {
        // TODO: test systemFingerprint
    }

    /**
     * Test the property '_object'
     */
    @Test
    void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'usage'
     */
    @Test
    void usageTest() {
        // TODO: test usage
    }

}
