/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.openapi.model.ProjectServiceAccountApiKey;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectServiceAccountCreateResponse
 */
class ProjectServiceAccountCreateResponseTest {
    private final ProjectServiceAccountCreateResponse model = new ProjectServiceAccountCreateResponse();

    /**
     * Model tests for ProjectServiceAccountCreateResponse
     */
    @Test
    void testProjectServiceAccountCreateResponse() {
        // TODO: test ProjectServiceAccountCreateResponse
    }

    /**
     * Test the property '_object'
     */
    @Test
    void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'role'
     */
    @Test
    void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'apiKey'
     */
    @Test
    void apiKeyTest() {
        // TODO: test apiKey
    }

}
