/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.openapi.model.RealtimeServerEventResponseContentPartAddedPart;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RealtimeServerEventResponseContentPartAdded
 */
class RealtimeServerEventResponseContentPartAddedTest {
    private final RealtimeServerEventResponseContentPartAdded model = new RealtimeServerEventResponseContentPartAdded();

    /**
     * Model tests for RealtimeServerEventResponseContentPartAdded
     */
    @Test
    void testRealtimeServerEventResponseContentPartAdded() {
        // TODO: test RealtimeServerEventResponseContentPartAdded
    }

    /**
     * Test the property 'eventId'
     */
    @Test
    void eventIdTest() {
        // TODO: test eventId
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'responseId'
     */
    @Test
    void responseIdTest() {
        // TODO: test responseId
    }

    /**
     * Test the property 'itemId'
     */
    @Test
    void itemIdTest() {
        // TODO: test itemId
    }

    /**
     * Test the property 'outputIndex'
     */
    @Test
    void outputIndexTest() {
        // TODO: test outputIndex
    }

    /**
     * Test the property 'contentIndex'
     */
    @Test
    void contentIndexTest() {
        // TODO: test contentIndex
    }

    /**
     * Test the property 'part'
     */
    @Test
    void partTest() {
        // TODO: test part
    }

}
