/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.openapi.model.RealtimeConversationItemWithReference;
import com.openai.openapi.model.RealtimeResponseCreateParamsConversation;
import com.openai.openapi.model.RealtimeResponseCreateParamsMaxResponseOutputTokens;
import com.openai.openapi.model.RealtimeResponseCreateParamsToolsInner;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RealtimeResponseCreateParams
 */
class RealtimeResponseCreateParamsTest {
    private final RealtimeResponseCreateParams model = new RealtimeResponseCreateParams();

    /**
     * Model tests for RealtimeResponseCreateParams
     */
    @Test
    void testRealtimeResponseCreateParams() {
        // TODO: test RealtimeResponseCreateParams
    }

    /**
     * Test the property 'modalities'
     */
    @Test
    void modalitiesTest() {
        // TODO: test modalities
    }

    /**
     * Test the property 'instructions'
     */
    @Test
    void instructionsTest() {
        // TODO: test instructions
    }

    /**
     * Test the property 'voice'
     */
    @Test
    void voiceTest() {
        // TODO: test voice
    }

    /**
     * Test the property 'outputAudioFormat'
     */
    @Test
    void outputAudioFormatTest() {
        // TODO: test outputAudioFormat
    }

    /**
     * Test the property 'tools'
     */
    @Test
    void toolsTest() {
        // TODO: test tools
    }

    /**
     * Test the property 'toolChoice'
     */
    @Test
    void toolChoiceTest() {
        // TODO: test toolChoice
    }

    /**
     * Test the property 'temperature'
     */
    @Test
    void temperatureTest() {
        // TODO: test temperature
    }

    /**
     * Test the property 'maxResponseOutputTokens'
     */
    @Test
    void maxResponseOutputTokensTest() {
        // TODO: test maxResponseOutputTokens
    }

    /**
     * Test the property 'conversation'
     */
    @Test
    void conversationTest() {
        // TODO: test conversation
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'input'
     */
    @Test
    void inputTest() {
        // TODO: test input
    }

}
