/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.openapi.model.RunStepCompletionUsage;
import com.openai.openapi.model.RunStepObjectLastError;
import com.openai.openapi.model.RunStepObjectStepDetails;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RunStepObject
 */
class RunStepObjectTest {
    private final RunStepObject model = new RunStepObject();

    /**
     * Model tests for RunStepObject
     */
    @Test
    void testRunStepObject() {
        // TODO: test RunStepObject
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property '_object'
     */
    @Test
    void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'assistantId'
     */
    @Test
    void assistantIdTest() {
        // TODO: test assistantId
    }

    /**
     * Test the property 'threadId'
     */
    @Test
    void threadIdTest() {
        // TODO: test threadId
    }

    /**
     * Test the property 'runId'
     */
    @Test
    void runIdTest() {
        // TODO: test runId
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'stepDetails'
     */
    @Test
    void stepDetailsTest() {
        // TODO: test stepDetails
    }

    /**
     * Test the property 'lastError'
     */
    @Test
    void lastErrorTest() {
        // TODO: test lastError
    }

    /**
     * Test the property 'expiredAt'
     */
    @Test
    void expiredAtTest() {
        // TODO: test expiredAt
    }

    /**
     * Test the property 'cancelledAt'
     */
    @Test
    void cancelledAtTest() {
        // TODO: test cancelledAt
    }

    /**
     * Test the property 'failedAt'
     */
    @Test
    void failedAtTest() {
        // TODO: test failedAt
    }

    /**
     * Test the property 'completedAt'
     */
    @Test
    void completedAtTest() {
        // TODO: test completedAt
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'usage'
     */
    @Test
    void usageTest() {
        // TODO: test usage
    }

}
