/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.openapi.model.CostsResult;
import com.openai.openapi.model.CostsResultAmount;
import com.openai.openapi.model.UsageAudioSpeechesResult;
import com.openai.openapi.model.UsageAudioTranscriptionsResult;
import com.openai.openapi.model.UsageCodeInterpreterSessionsResult;
import com.openai.openapi.model.UsageCompletionsResult;
import com.openai.openapi.model.UsageEmbeddingsResult;
import com.openai.openapi.model.UsageImagesResult;
import com.openai.openapi.model.UsageModerationsResult;
import com.openai.openapi.model.UsageVectorStoresResult;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UsageTimeBucketResultInner
 */
class UsageTimeBucketResultInnerTest {
    private final UsageTimeBucketResultInner model = new UsageTimeBucketResultInner();

    /**
     * Model tests for UsageTimeBucketResultInner
     */
    @Test
    void testUsageTimeBucketResultInner() {
        // TODO: test UsageTimeBucketResultInner
    }

    /**
     * Test the property '_object'
     */
    @Test
    void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'inputTokens'
     */
    @Test
    void inputTokensTest() {
        // TODO: test inputTokens
    }

    /**
     * Test the property 'inputCachedTokens'
     */
    @Test
    void inputCachedTokensTest() {
        // TODO: test inputCachedTokens
    }

    /**
     * Test the property 'outputTokens'
     */
    @Test
    void outputTokensTest() {
        // TODO: test outputTokens
    }

    /**
     * Test the property 'inputAudioTokens'
     */
    @Test
    void inputAudioTokensTest() {
        // TODO: test inputAudioTokens
    }

    /**
     * Test the property 'outputAudioTokens'
     */
    @Test
    void outputAudioTokensTest() {
        // TODO: test outputAudioTokens
    }

    /**
     * Test the property 'numModelRequests'
     */
    @Test
    void numModelRequestsTest() {
        // TODO: test numModelRequests
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'apiKeyId'
     */
    @Test
    void apiKeyIdTest() {
        // TODO: test apiKeyId
    }

    /**
     * Test the property 'model'
     */
    @Test
    void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'batch'
     */
    @Test
    void batchTest() {
        // TODO: test batch
    }

    /**
     * Test the property 'images'
     */
    @Test
    void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'source'
     */
    @Test
    void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'size'
     */
    @Test
    void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'characters'
     */
    @Test
    void charactersTest() {
        // TODO: test characters
    }

    /**
     * Test the property 'seconds'
     */
    @Test
    void secondsTest() {
        // TODO: test seconds
    }

    /**
     * Test the property 'usageBytes'
     */
    @Test
    void usageBytesTest() {
        // TODO: test usageBytes
    }

    /**
     * Test the property 'numSessions'
     */
    @Test
    void numSessionsTest() {
        // TODO: test numSessions
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'lineItem'
     */
    @Test
    void lineItemTest() {
        // TODO: test lineItem
    }

}
