/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openai.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.openapi.model.VectorStoreFileObjectChunkingStrategy;
import com.openai.openapi.model.VectorStoreFileObjectLastError;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VectorStoreFileObject
 */
class VectorStoreFileObjectTest {
    private final VectorStoreFileObject model = new VectorStoreFileObject();

    /**
     * Model tests for VectorStoreFileObject
     */
    @Test
    void testVectorStoreFileObject() {
        // TODO: test VectorStoreFileObject
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property '_object'
     */
    @Test
    void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'usageBytes'
     */
    @Test
    void usageBytesTest() {
        // TODO: test usageBytes
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'vectorStoreId'
     */
    @Test
    void vectorStoreIdTest() {
        // TODO: test vectorStoreId
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'lastError'
     */
    @Test
    void lastErrorTest() {
        // TODO: test lastError
    }

    /**
     * Test the property 'chunkingStrategy'
     */
    @Test
    void chunkingStrategyTest() {
        // TODO: test chunkingStrategy
    }

}
