/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuditLogOrganizationUpdatedChangesRequestedSettings
 */
class AuditLogOrganizationUpdatedChangesRequestedSettingsTest {
    private final AuditLogOrganizationUpdatedChangesRequestedSettings model = new AuditLogOrganizationUpdatedChangesRequestedSettings();

    /**
     * Model tests for AuditLogOrganizationUpdatedChangesRequestedSettings
     */
    @Test
    void testAuditLogOrganizationUpdatedChangesRequestedSettings() {
        // TODO: test AuditLogOrganizationUpdatedChangesRequestedSettings
    }

    /**
     * Test the property 'threadsUiVisibility'
     */
    @Test
    void threadsUiVisibilityTest() {
        // TODO: test threadsUiVisibility
    }

    /**
     * Test the property 'usageDashboardVisibility'
     */
    @Test
    void usageDashboardVisibilityTest() {
        // TODO: test usageDashboardVisibility
    }

}
