/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import org.openapitools.client.model.ArrayOfContentPartsInner;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateMessageRequestContent
 */
class CreateMessageRequestContentTest {
    private final CreateMessageRequestContent model = new CreateMessageRequestContent();

    /**
     * Model tests for CreateMessageRequestContent
     */
    @Test
    void testCreateMessageRequestContent() {
        // TODO: test CreateMessageRequestContent
    }

}
