/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.CreateAssistantRequestToolResourcesFileSearchVectorStoresInnerChunkingStrategy;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateThreadRequestToolResourcesFileSearchVectorStoresInner
 */
class CreateThreadRequestToolResourcesFileSearchVectorStoresInnerTest {
    private final CreateThreadRequestToolResourcesFileSearchVectorStoresInner model = new CreateThreadRequestToolResourcesFileSearchVectorStoresInner();

    /**
     * Model tests for CreateThreadRequestToolResourcesFileSearchVectorStoresInner
     */
    @Test
    void testCreateThreadRequestToolResourcesFileSearchVectorStoresInner() {
        // TODO: test CreateThreadRequestToolResourcesFileSearchVectorStoresInner
    }

    /**
     * Test the property 'fileIds'
     */
    @Test
    void fileIdsTest() {
        // TODO: test fileIds
    }

    /**
     * Test the property 'chunkingStrategy'
     */
    @Test
    void chunkingStrategyTest() {
        // TODO: test chunkingStrategy
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

}
