/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MessageDeltaContentImageFileObjectImageFile
 */
class MessageDeltaContentImageFileObjectImageFileTest {
    private final MessageDeltaContentImageFileObjectImageFile model = new MessageDeltaContentImageFileObjectImageFile();

    /**
     * Model tests for MessageDeltaContentImageFileObjectImageFile
     */
    @Test
    void testMessageDeltaContentImageFileObjectImageFile() {
        // TODO: test MessageDeltaContentImageFileObjectImageFile
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'detail'
     */
    @Test
    void detailTest() {
        // TODO: test detail
    }

}
