/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.MessageDeltaObjectDeltaContentInner;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MessageDeltaObjectDelta
 */
class MessageDeltaObjectDeltaTest {
    private final MessageDeltaObjectDelta model = new MessageDeltaObjectDelta();

    /**
     * Model tests for MessageDeltaObjectDelta
     */
    @Test
    void testMessageDeltaObjectDelta() {
        // TODO: test MessageDeltaObjectDelta
    }

    /**
     * Test the property 'role'
     */
    @Test
    void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'content'
     */
    @Test
    void contentTest() {
        // TODO: test content
    }

}
