/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProjectApiKey;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectApiKeyListResponse
 */
class ProjectApiKeyListResponseTest {
    private final ProjectApiKeyListResponse model = new ProjectApiKeyListResponse();

    /**
     * Model tests for ProjectApiKeyListResponse
     */
    @Test
    void testProjectApiKeyListResponse() {
        // TODO: test ProjectApiKeyListResponse
    }

    /**
     * Test the property '_object'
     */
    @Test
    void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'firstId'
     */
    @Test
    void firstIdTest() {
        // TODO: test firstId
    }

    /**
     * Test the property 'lastId'
     */
    @Test
    void lastIdTest() {
        // TODO: test lastId
    }

    /**
     * Test the property 'hasMore'
     */
    @Test
    void hasMoreTest() {
        // TODO: test hasMore
    }

}
