/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.RealtimeConversationItem;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RealtimeClientEventConversationItemCreate
 */
class RealtimeClientEventConversationItemCreateTest {
    private final RealtimeClientEventConversationItemCreate model = new RealtimeClientEventConversationItemCreate();

    /**
     * Model tests for RealtimeClientEventConversationItemCreate
     */
    @Test
    void testRealtimeClientEventConversationItemCreate() {
        // TODO: test RealtimeClientEventConversationItemCreate
    }

    /**
     * Test the property 'eventId'
     */
    @Test
    void eventIdTest() {
        // TODO: test eventId
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'previousItemId'
     */
    @Test
    void previousItemIdTest() {
        // TODO: test previousItemId
    }

    /**
     * Test the property 'item'
     */
    @Test
    void itemTest() {
        // TODO: test item
    }

}
