/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RealtimeResponseUsageOutputTokenDetails
 */
class RealtimeResponseUsageOutputTokenDetailsTest {
    private final RealtimeResponseUsageOutputTokenDetails model = new RealtimeResponseUsageOutputTokenDetails();

    /**
     * Model tests for RealtimeResponseUsageOutputTokenDetails
     */
    @Test
    void testRealtimeResponseUsageOutputTokenDetails() {
        // TODO: test RealtimeResponseUsageOutputTokenDetails
    }

    /**
     * Test the property 'textTokens'
     */
    @Test
    void textTokensTest() {
        // TODO: test textTokens
    }

    /**
     * Test the property 'audioTokens'
     */
    @Test
    void audioTokensTest() {
        // TODO: test audioTokens
    }

}
