/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TranscriptionWord
 */
class TranscriptionWordTest {
    private final TranscriptionWord model = new TranscriptionWord();

    /**
     * Model tests for TranscriptionWord
     */
    @Test
    void testTranscriptionWord() {
        // TODO: test TranscriptionWord
    }

    /**
     * Test the property 'word'
     */
    @Test
    void wordTest() {
        // TODO: test word
    }

    /**
     * Test the property 'start'
     */
    @Test
    void startTest() {
        // TODO: test start
    }

    /**
     * Test the property 'end'
     */
    @Test
    void endTest() {
        // TODO: test end
    }

}
