/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.OtherChunkingStrategyResponseParam;
import org.openapitools.client.model.StaticChunkingStrategy;
import org.openapitools.client.model.StaticChunkingStrategyResponseParam;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VectorStoreFileObjectChunkingStrategy
 */
class VectorStoreFileObjectChunkingStrategyTest {
    private final VectorStoreFileObjectChunkingStrategy model = new VectorStoreFileObjectChunkingStrategy();

    /**
     * Model tests for VectorStoreFileObjectChunkingStrategy
     */
    @Test
    void testVectorStoreFileObjectChunkingStrategy() {
        // TODO: test VectorStoreFileObjectChunkingStrategy
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property '_static'
     */
    @Test
    void _staticTest() {
        // TODO: test _static
    }

}
