/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VectorStoreFileBatchObjectFileCounts
 */
class VectorStoreFileBatchObjectFileCountsTest {
    private final VectorStoreFileBatchObjectFileCounts model = new VectorStoreFileBatchObjectFileCounts();

    /**
     * Model tests for VectorStoreFileBatchObjectFileCounts
     */
    @Test
    void testVectorStoreFileBatchObjectFileCounts() {
        // TODO: test VectorStoreFileBatchObjectFileCounts
    }

    /**
     * Test the property 'inProgress'
     */
    @Test
    void inProgressTest() {
        // TODO: test inProgress
    }

    /**
     * Test the property 'completed'
     */
    @Test
    void completedTest() {
        // TODO: test completed
    }

    /**
     * Test the property 'failed'
     */
    @Test
    void failedTest() {
        // TODO: test failed
    }

    /**
     * Test the property 'cancelled'
     */
    @Test
    void cancelledTest() {
        // TODO: test cancelled
    }

    /**
     * Test the property 'total'
     */
    @Test
    void totalTest() {
        // TODO: test total
    }

}
