/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ChatCompletionMessageToolCall;
import org.openapitools.client.model.ChatCompletionResponseMessageAudio;
import org.openapitools.client.model.ChatCompletionResponseMessageFunctionCall;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * A chat completion message generated by the model.
 */
@JsonPropertyOrder({
  ChatCompletionResponseMessage.JSON_PROPERTY_CONTENT,
  ChatCompletionResponseMessage.JSON_PROPERTY_REFUSAL,
  ChatCompletionResponseMessage.JSON_PROPERTY_TOOL_CALLS,
  ChatCompletionResponseMessage.JSON_PROPERTY_ROLE,
  ChatCompletionResponseMessage.JSON_PROPERTY_FUNCTION_CALL,
  ChatCompletionResponseMessage.JSON_PROPERTY_AUDIO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:51:07.087747877-05:00[US/Eastern]", comments = "Generator version: 7.11.0")
public class ChatCompletionResponseMessage {
  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nullable
  private String content;

  public static final String JSON_PROPERTY_REFUSAL = "refusal";
  @javax.annotation.Nullable
  private String refusal;

  public static final String JSON_PROPERTY_TOOL_CALLS = "tool_calls";
  @javax.annotation.Nullable
  private List<ChatCompletionMessageToolCall> toolCalls = new ArrayList<>();

  /**
   * The role of the author of this message.
   */
  public enum RoleEnum {
    ASSISTANT(String.valueOf("assistant"));

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RoleEnum fromValue(String value) {
      for (RoleEnum b : RoleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nonnull
  private RoleEnum role;

  public static final String JSON_PROPERTY_FUNCTION_CALL = "function_call";
  @javax.annotation.Nullable
  private ChatCompletionResponseMessageFunctionCall functionCall;

  public static final String JSON_PROPERTY_AUDIO = "audio";
  @javax.annotation.Nullable
  private JsonNullable<ChatCompletionResponseMessageAudio> audio = JsonNullable.<ChatCompletionResponseMessageAudio>undefined();

  public ChatCompletionResponseMessage() {
  }

  public ChatCompletionResponseMessage content(@javax.annotation.Nullable String content) {
    
    this.content = content;
    return this;
  }

  /**
   * The contents of the message.
   * @return content
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getContent() {
    return content;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@javax.annotation.Nullable String content) {
    this.content = content;
  }

  public ChatCompletionResponseMessage refusal(@javax.annotation.Nullable String refusal) {
    
    this.refusal = refusal;
    return this;
  }

  /**
   * The refusal message generated by the model.
   * @return refusal
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFUSAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRefusal() {
    return refusal;
  }


  @JsonProperty(JSON_PROPERTY_REFUSAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRefusal(@javax.annotation.Nullable String refusal) {
    this.refusal = refusal;
  }

  public ChatCompletionResponseMessage toolCalls(@javax.annotation.Nullable List<ChatCompletionMessageToolCall> toolCalls) {
    
    this.toolCalls = toolCalls;
    return this;
  }

  public ChatCompletionResponseMessage addToolCallsItem(ChatCompletionMessageToolCall toolCallsItem) {
    if (this.toolCalls == null) {
      this.toolCalls = new ArrayList<>();
    }
    this.toolCalls.add(toolCallsItem);
    return this;
  }

  /**
   * The tool calls generated by the model, such as function calls.
   * @return toolCalls
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOOL_CALLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ChatCompletionMessageToolCall> getToolCalls() {
    return toolCalls;
  }


  @JsonProperty(JSON_PROPERTY_TOOL_CALLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToolCalls(@javax.annotation.Nullable List<ChatCompletionMessageToolCall> toolCalls) {
    this.toolCalls = toolCalls;
  }

  public ChatCompletionResponseMessage role(@javax.annotation.Nonnull RoleEnum role) {
    
    this.role = role;
    return this;
  }

  /**
   * The role of the author of this message.
   * @return role
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RoleEnum getRole() {
    return role;
  }


  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRole(@javax.annotation.Nonnull RoleEnum role) {
    this.role = role;
  }

  public ChatCompletionResponseMessage functionCall(@javax.annotation.Nullable ChatCompletionResponseMessageFunctionCall functionCall) {
    
    this.functionCall = functionCall;
    return this;
  }

  /**
   * Get functionCall
   * @return functionCall
   * @deprecated
   */
  @Deprecated
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNCTION_CALL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChatCompletionResponseMessageFunctionCall getFunctionCall() {
    return functionCall;
  }


  @JsonProperty(JSON_PROPERTY_FUNCTION_CALL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFunctionCall(@javax.annotation.Nullable ChatCompletionResponseMessageFunctionCall functionCall) {
    this.functionCall = functionCall;
  }

  public ChatCompletionResponseMessage audio(@javax.annotation.Nullable ChatCompletionResponseMessageAudio audio) {
    this.audio = JsonNullable.<ChatCompletionResponseMessageAudio>of(audio);
    
    return this;
  }

  /**
   * Get audio
   * @return audio
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public ChatCompletionResponseMessageAudio getAudio() {
        return audio.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AUDIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ChatCompletionResponseMessageAudio> getAudio_JsonNullable() {
    return audio;
  }
  
  @JsonProperty(JSON_PROPERTY_AUDIO)
  public void setAudio_JsonNullable(JsonNullable<ChatCompletionResponseMessageAudio> audio) {
    this.audio = audio;
  }

  public void setAudio(@javax.annotation.Nullable ChatCompletionResponseMessageAudio audio) {
    this.audio = JsonNullable.<ChatCompletionResponseMessageAudio>of(audio);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionResponseMessage chatCompletionResponseMessage = (ChatCompletionResponseMessage) o;
    return Objects.equals(this.content, chatCompletionResponseMessage.content) &&
        Objects.equals(this.refusal, chatCompletionResponseMessage.refusal) &&
        Objects.equals(this.toolCalls, chatCompletionResponseMessage.toolCalls) &&
        Objects.equals(this.role, chatCompletionResponseMessage.role) &&
        Objects.equals(this.functionCall, chatCompletionResponseMessage.functionCall) &&
        equalsNullable(this.audio, chatCompletionResponseMessage.audio);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, refusal, toolCalls, role, functionCall, hashCodeNullable(audio));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionResponseMessage {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    refusal: ").append(toIndentedString(refusal)).append("\n");
    sb.append("    toolCalls: ").append(toIndentedString(toolCalls)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    functionCall: ").append(toIndentedString(functionCall)).append("\n");
    sb.append("    audio: ").append(toIndentedString(audio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `content` to the URL query string
    if (getContent() != null) {
      try {
        joiner.add(String.format("%scontent%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getContent()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `refusal` to the URL query string
    if (getRefusal() != null) {
      try {
        joiner.add(String.format("%srefusal%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRefusal()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `tool_calls` to the URL query string
    if (getToolCalls() != null) {
      for (int i = 0; i < getToolCalls().size(); i++) {
        if (getToolCalls().get(i) != null) {
          joiner.add(getToolCalls().get(i).toUrlQueryString(String.format("%stool_calls%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `role` to the URL query string
    if (getRole() != null) {
      try {
        joiner.add(String.format("%srole%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRole()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `function_call` to the URL query string
    if (getFunctionCall() != null) {
      joiner.add(getFunctionCall().toUrlQueryString(prefix + "function_call" + suffix));
    }

    // add `audio` to the URL query string
    if (getAudio() != null) {
      joiner.add(getAudio().toUrlQueryString(prefix + "audio" + suffix));
    }

    return joiner.toString();
  }

}

